### ISSUE TITLE
Documentation does not fit pipeline behaviour.

### ISSUE THREAD

**Issue by oliverdrechsel** [nf-core/differentialabundance#156] opened 2023-09-05 14:25 UTC
### Description of the bug

https://nf-co.re/differentialabundance/1.2.0/docs/usage mentions in section Contrasts file
`blocking` is listed under optional arguments. 

Leaving out this column from contrasts file, the pipeline will complain 
```
  Error in read_contrasts(contrasts_file, samples) :
    Contrasts file must contain all of variable, reference, target, blocking
  Calls: validate_inputs -> read_contrasts
  Execution halted
```

---------------------------------------------------

In addtion documentation's Quick start mentions 
`-profile rnaseq`

using this profile will cause an error message that this profile is not defined
```
Unknown configuration profile: 'rnaseq'
```

### Command used and terminal output

```console
# this call fuses both issues

$ nextflow run nf-core/differentialabundance      \
--input samplesheet.csv      \
--contrasts contrasts_small.noblocking.csv      \
--matrix salmon.merged.gene_counts.tsv      \
--gtf references/Homo_sapiens.GRCh37.87.gtf      \
--outdir test_output      \
-profile rnaseq,rki_slurm,rki_singularity,singularity
```

### Relevant files

```
# contrasts file

id,variable,reference,target,exclude_samples_col,exclude_samples_values
infected_time_comparison,incubation,15,24,condition,control
```

### System information

N E X T F L O W  ~  version 23.04.1
`https://github.com/nf-core/differentialabundance` [determined_waddington] DSL2 - revision: 3a849f0469 [master]

**Comment by WackerO** [comment] 2023-10-05 11:12
Hey there @oliverdrechsel 

So regarding the unknown profile I am very sorry, but I cannot reproduce that error...I just ran the pipeline with that profile and it worked just fine; it is defined in the nextflow.config.

Regarding the problem with the contrasts file, your layout is not correct. I can see how the docu is a bit unclear in that regard, I will update it.
I'm not quite sure what the contrasts should look like in your case but I believe it might be this?

```
id,variable,reference,target,blocking
infected_time_comparison,incubation,15,24,condition
```

That is to say, the header of the csv file has to be the same always; the _entry_ for blocking can be left out, but the word blocking itself still has to appear in the header row. I'll specify this in the docs :)

I'm closing this for now, don't hesitate to reopen if you still have trouble with the pipeline!

**Comment by WackerO** [comment] 2023-10-05 11:20
Just had a look at the code, my bad; the optional columns are treated a bit differently right now, i.e. exclude_samples_col and exclude_samples_values are truly optional whereas for blocking, at least the column name seems to be necessary right now. Will see if I can change this during the hackathon 💪

**Comment by pinin4fjords** [comment] 2023-10-18 08:51
https://github.com/nf-core/differentialabundance/pull/175, combined with https://github.com/pinin4fjords/shinyngs/pull/57, addresses this issue.

**Closed** 2023-10-18 08:52 UTC
Labels: bug
