### ISSUE TITLE
Bad job name on LSF (too long, special chars?)

### ISSUE THREAD

**Issue by colindaven** [nf-core/differentialabundance#134] opened 2023-06-02 08:37 UTC
### Description of the bug

Thanks for this nice pipeline, which is a valuable addition for RNA-seq.

It looks like the LSF scheduler does not like either the length of the job name, or the special characters in the job name

Local job submission works, just not LSF.

### Command used and terminal output

```console
[de/097cc9] Submitted process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:VALIDATOR (samplesheet1.csv)
Error executing process > 'NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:CUSTOM_MATRIXFILTER ([id:study])'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed [/mnt/path/nfcore_diffabund/nf-core-differentialabundance-1.2.0/workflow/./workflows/../modules/nf-core/custom/matrixfilter/templates/matrixfilter.R]:

  bsub

Command exit status:
  255

Command output:
  Bad job name. Job not submitted.
```

### System information

Local LSF HPC using singularity. Local job submission works, just not LSF.

Diff Abund ver 1.2.0.

**Comment by pinin4fjords** [comment] 2023-10-05 08:54
Thanks for the report, and for raising this. I feel like it's non-specific to this workflow though, and rather an issue with the Nextflow/ LSF interface (thank you for raising the other issue), so closing here.

**Closed by pinin4fjords** 2023-10-05 08:54 UTC
Labels: bug

**Comment by BEFH** [comment] 2024-03-08 19:17
This is somewhat specific to this workflow. The issue is not the length of the job name but the fact that it has square brackets in the name, which is reserved for job arrays. I have a pull request here in Nextflow that will fix the issue:

https://github.com/nextflow-io/nextflow/pull/4799

However, it is probably bad practice to use square brackets.

**Comment by BEFH** [comment] 2024-03-10 19:20
My pull request that fixes this has been merged into the Nextflow repo and should be in the next version.
