### ISSUE TITLE
Switching to rlog for deseq2 vs method truncates pipeline output

### ISSUE THREAD

**Issue by tfalkarkea** [nf-core/differentialabundance#187] opened 2023-11-03 19:38 UTC
### Description of the bug

Selecting rlog as the DESeq2 VS method (which is recommended be DESeq when the vst_nsub number is too high for the amount of counts in the provided dataset) skips plotting and notebook generating steps. 

### Command used and terminal output

```console
nextflow run nf-core/differentialabundance -profile docker,test_full --outdir test_full --deseq2_vs_method rlog

N E X T F L O W  ~  version 23.04.1
NOTE: Your local project version looks outdated - a different revision is available in the remote repository [44c449be0a]
Launching `https://github.com/nf-core/differentialabundance` [dreamy_church] DSL2 - revision: 3a849f0469 [master]


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/differentialabundance v1.2.0-g3a849f0
------------------------------------------------------
Core Nextflow options
  revision                   : master
  runName                    : dreamy_church
  containerEngine            : docker
  launchDir                  : /home/tfalk/differentialabundance
  workDir                    : /home/tfalk/differentialabundance/work
  projectDir                 : /home/tfalk/.nextflow/assets/nf-core/differentialabundance
  userName                   : tfalk
  profile                    : docker,test_full
  configFiles                : /home/tfalk/.nextflow/assets/nf-core/differentialabundance/nextflow.config, /home/tfalk/differentialabundance/nextflow.config

Input/output options
  input                      : https://raw.githubusercontent.com/nf-core/test-datasets/differentialabundance/testdata/rnaseq_featurecounts_sample_preparations.tsv
  contrasts                  : https://raw.githubusercontent.com/nf-core/test-datasets/differentialabundance/testdata/rnaseq_featurecounts_contrast_file.csv
  outdir                     : test_full

Abundance values
  matrix                     : https://raw.githubusercontent.com/nf-core/test-datasets/differentialabundance/testdata/rnaseq_featurecounts_merged_gene_counts.txt
  affy_cel_files_archive     : null

Observations (e.g. samples) options
  observations_id_col        : Secondary Name
  observations_name_col      : Lab ID

Affy input options
  affy_cdfname               : null

Exploratory analysis
  exploratory_palette_name   : Dark2

DESeq2 specific options (RNA-seq only)
  deseq2_vs_method           : rlog

Limma specific options (microarray only)
  limma_spacing              : null
  limma_block                : null
  limma_correlation          : null

GSEA
  gsea_run                   : true
  gsea_gene_sets             : https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/mus_musculus/gene_set_analysis/mh.all.v2022.1.Mm.symbols.gmt

Shiny app settings
  shinyngs_shinyapps_account : null
  shinyngs_shinyapps_app_name: null

Reporting options
  report_file                : /home/tfalk/.nextflow/assets/nf-core/differentialabundance/assets/differentialabundance_report.Rmd
  logo_file                  : /home/tfalk/.nextflow/assets/nf-core/differentialabundance/docs/images/nf-core-differentialabundance_logo_light.png
  css_file                   : /home/tfalk/.nextflow/assets/nf-core/differentialabundance/assets/nf-core_style.css
  citations_file             : /home/tfalk/.nextflow/assets/nf-core/differentialabundance/CITATIONS.md
  report_title               : full tests
  report_author              : nf-core elves
  report_description         : This is a full-sized test dataset contributed by Oskar Wacker

Reference genome options
  gtf                        : https://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz

Institutional config options
  config_profile_name        : Full test profile
  config_profile_description : Full test dataset to check pipeline function

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/differentialabundance for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.7568000

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/differentialabundance/blob/master/CITATIONS.md
------------------------------------------------------
executor >  local (13)
[0e/b95043] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GUNZIP_GTF (Mus_musculus.GRCm38.81.gtf.gz)                        [100%] 1 of 1 ✔
[74/3d07d4] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GTF_TO_TABLE (Mus_musculus)                                       [100%] 1 of 1 ✔
[b4/9eb11f] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:VALIDATOR (rnaseq_featurecounts_sample_preparations.tsv)          [100%] 1 of 1 ✔
[79/da9465] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:CUSTOM_MATRIXFILTER ([id:study])                                  [100%] 1 of 1 ✔
[fb/db2553] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:DESEQ2_DIFFERENTIAL ([id:Condition_genotype_WT_KO, variable:Co... [100%] 2 of 2 ✔
[e0/a4e669] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:CUSTOM_TABULARTOGSEAGCT (Condition_treatment_Control_Treated)     [100%] 1 of 1 ✔
[87/c45994] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:CUSTOM_TABULARTOGSEACLS (Condition_treatment_Control_Treated)     [100%] 2 of 2 ✔
[c0/98fdbf] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:TABULAR_TO_GSEA_CHIP (1)                                          [100%] 1 of 1 ✔
[f6/50e665] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (Condition_treatment_Control_Treated)                   [100%] 2 of 2 ✔
[-        ] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:PLOT_EXPLORATORY                                                  -
[-        ] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:PLOT_DIFFERENTIAL                                                 -
[78/2346ed] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:CUSTOM_DUMPSOFTWAREVERSIONS (1)                                   [100%] 1 of 1 ✔
[-        ] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:SHINYNGS_APP                                                      -
[-        ] process > NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:RMARKDOWNNOTEBOOK                                                 -
-[nf-core/differentialabundance] Pipeline completed successfully-
Completed at: 03-Nov-2023 15:31:06
Duration    : 3m 58s
CPU hours   : 0.3
Succeeded   : 13
```

### System information

nextflow version 23.04.1.5866, nf-core/differentialabundance v1.2.0-g3a849f0

**Comment by WackerO** [comment] 2023-11-09 08:56
Hey @tfalkarkea, I just tried to reproduce that error with my local installation of diffab and did not manage to; all modules run for me. Unfortunately, your exact command does not work for me because of some stupid docker error, but I'm right now seeing if I can reproduce the error with singularity.
My nextflow version is newer than yours, however, so possibly that is what fixes this issue? Could you try updating to nextflow=23.10.0 and rerunning?

**Comment by WackerO** [comment] 2023-11-09 09:05
Alright, with singularity the online pipeline version worked, but indeed it skipped some modules. Will see if I can figure out the reason

**Comment by WackerO** [comment] 2023-11-09 10:08
Okay, so for some reason, the first time I used the command, nextflow pulled an old version, just as it did for @tfalkarkea (nf-core/differentialabundance v1.2.0-g3a849f0; I think for me it was version 1.2.1). I'm not sure why this happens as it should actually default to the newest version, which is 1.3.1. You can ensure that that version is run by adding `-r 1.3.1` to your execution command, then everything should run fine :) I will close this for now, please do re-open if it does not work for you!

**Closed by WackerO** 2023-11-09 10:08 UTC
Labels: bug

**Comment by tfalkarkea** [comment] 2023-11-09 14:04
Thanks for taking a look! Glad it could be fixed.
